# .github/workflows/deploy.yml
name: Deploy Branches to GitHub Pages

on:
  push:
    branches:
      - main
      - dev
      - uix-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Force Node.js 24
      - name: Force Node.js 24
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      # Checkout the current branch
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set deploy folder based on branch
      - name: Set deploy folder
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "FOLDER=." >> $GITHUB_ENV
          else
            echo "FOLDER=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      # Prepare deploy files
      - name: Prepare deploy files
        run: |
          mkdir -p deploy
          # Remove old files for this branch only
          if [ "$FOLDER" != "." ]; then rm -rf deploy/$FOLDER; fi
          # Copy all files except .git and workflows
          rsync -av --exclude='.git' --exclude='.github' ./ deploy/$FOLDER/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          keep_files: true
